### ISSUE TITLE
Product Page location [discussion]

### ISSUE THREAD

**Issue by katalysis** [concretecms-community-store/community_store#175]
I'm wondering if it would be helpful to have an option within the product dashboard to place product pages within the the sitemap tree as an alternative to storing them under a general 'Products' page.

The advantages of this to my mind are:

- A logical navigation structure where users can navigate using breadcrumbs and menus can indicate that they are within an active category.

- SEO benefit of the product sitting within a relevant category e.g. home/widgets/widget-plus rather than home/products/widget-plus

- Easy for users to understand

I know there has been a bit of discussion around this in #105 particularly with a view to products included in multiple categories but I think it would be nice if there was an option to decide which approach to take.

Something like this:

![choose-location](https://cloud.githubusercontent.com/assets/4235012/22077494/50fce12c-ddac-11e6-9da5-a860a57c5f6e.png)

Optionally there could be an addition to settings to enable this:

![products-settings](https://cloud.githubusercontent.com/assets/4235012/22077780/7f15c87a-ddad-11e6-97bd-2c82c4569068.png)

**Comment by Mesuva** [comment]
I don't see any problem with this, I agree that in some shops is makes sense to use the page paths and categorisation for SEO.

As it currently stands the product pages can be moved in the sitemap without any issues, you can just go to the sitemap and move them around as with any other page, but what you're describing here is making the process more part of creating the product in the first place.

With that suggested 'Include option to publish pages anywhere' checked, perhaps a new page selector would appear on the 'Detail Page' tab of the product. It would default to the default page selected, but could then easily be changed. 

That's likely to be a quick feature to be able to add, the product dashboard page just need to look for a target parent page when creating, otherwise it would behave as it does now and falls back to the default location.

**Comment by blinkwayne** [comment]
is there a way to change the detail page for a product after it's set the first time?

**Comment by katalysis** [comment]
You can just move it around in the sitemap.
