### ISSUE TITLE
Purchase history in user profile

### ISSUE THREAD

**Issue by cahueya** [concretecms-community-store/community_store#209]
Are there any plans to integrate the purchase history into user profiles?

**Comment by justynpride** [comment]
I agree this would be a fantastic feature to add in

**Comment by dbuonomo** [comment]
My team is developing a customer manager that includes purchase history. It is a bit of a composition of concrete5 members and community store orders, bundled into a separate package.

Parts of the package are specific to our application, but I could strip that out and make it available within a couple of weeks.

**Comment by justynpride** [comment]
Sounds like a great option

**Comment by Mesuva** [comment]
@dbuonomo Just wondering if you've made any progress with this?  
I'm looking to start on adding some purchase history screens (into the backend first) and I wouldn't want to duplicate efforts.

**Comment by cahueya** [comment]
any news on this?

**Comment by justynpride** [comment]
any update?

**Comment by dbuonomo** [comment]
Sorry for the delay in responding.

The original version of this package that I mentioned back in March is basically a copy of the native c5 user manager (Members) that is integrated with Community Store. It's evolved a lot since then, so I need to decide weather to put the original version out on a repository or remove those application specific features and use the current version. There are also some v8 rendering issues to resolve - nothing huge.

Can you tell me more specifically what you are looking to do with this. It will help inform my decision.

**Comment by krebbi** [comment]
sounds a bit like it has the potential to be a marketplace as well..?

**Comment by justynpride** [comment]
I’d mainly been wanting to have a location for an order history. Having a place for customers can go does lead to other thoughts for help and contact areas.

**Comment by justynpride** [comment]
any update?

**Comment by ebell14** [comment]
I agree with @justynpride @dbuonomo, the ability to include past orders would be a good place to start, Shopify does a very nice job with this feature and goes a few steps further.

**Comment by drumrby** [comment]
Has there been any movement on this? I as well, am looking for this functionality.

**Comment by cahueya** [comment]
Has any of you guys had any effort for this? I am happy to place this as a job request if anyone would want to do it.

**Comment by typoman76** [comment]
There is now a solution from @JeRoNZ in his github repo: https://github.com/JeRoNZ/community_store_order_history
