### ISSUE TITLE
Including custom Product Attributes in general search

### ISSUE THREAD

**Issue by craigmarcussen** [concretecms-community-store/community_store#527]
Hello,

This is not really an issue... it is more of a question.

I love the ability to create custom attributes for the store, but I need them to register in a general search. I am not great with PHP (I can understand it, but I am just fair at writing it). I have been able to add the product attributes to my custom List Page and Product Page templates by examining how it is done with other elements. Now I just need them to be included in a search. Is there specific code I need to add to the custom template I have created for Products?

Thanks,
Craig

**Comment by Mesuva** [comment]
Hi Craig, I'm understanding what you are describing here.

Product attributes and their associated indexing data are stored separately to attributes of other types (pages, users, files), so they aren't included in the data that is looked through from the site-wise search. The site-wise search is only going to look at _page_ attribute data.

When product pages are created, it does copy into the page's meta description attribute the product's short description, so that does help with searching - but doesn't quite solve what you are after here.

The other thing that happens is that product blocks have a `getSearchableContent` function on them, that the search indexing uses to work out what the actual text content of a product block is to use for page searching. By default that gets the name, SKU, description and detail, but again doesn't look more specifically at product attributes.

Going forward, I think it would be a good idea for me to adjust this getSearchableContent function to also use product attributes that have been marked with 'Content included in search index.'

But in the meanwhile, what you could do is drop in a product block controller override to force the product block to add more attribute data to the search.

You would drop into a file at /application/blocks/community_product/controller.php :

```
<?php
namespace Application\Block\CommunityProduct;
use Concrete\Package\CommunityStore\Src\CommunityStore\Product\Product as StoreProduct;

class Controller extends \Concrete\Package\CommunityStore\Block\CommunityProduct\Controller
{
    public function getSearchableContent()
    {
        $product = false;

        if ('page' == $this->productLocation) {
            $page = $this->getCollectionObject();

            if ($page) {
                $cID = $page->getCollectionID();
                $product = StoreProduct::getByCollectionID($cID);
            }
        } else {
            $product = StoreProduct::getByID($this->pID);
        }

        if ($product) {
            $sku = $product->getSKU();

            $extraSearch = $product->getAttribute('test_search');

            return $product->getName() . ($sku ? ' (' . $sku . ')' : '') . ' ' . $product->getDesc() . ' ' . $product->getDetail() . ' ' .$extraSearch;
        } else {
            return '';
        }
    }
}
```

You'll spot where I define $extraSearch - it's on that line you'd change the handle of the product attribute you want included in the search data. Then re-run your 'Index Search Engine - All' automated job, and you should find data in that attributes returned in the search.

**Comment by craigmarcussen** [comment]
Mesuva,

That worked perfectly! Thank you so much for taking the time to put together that detailed email, and for writing the code block to make it all work.

I love Concrete5, and have used it for many sites over the years. The only major issue I have is with the search functionality. It seems difficult to include custom elements from Add-Ons into the search index. And with a shopping site, clients are always asking for everything in the site to be searchable. I think adding the functionality you mentioned (to attributes tagged with the **Content included in search index**) would be a terrific addition.

Again, thank you for taking the time to reply and help. I would love to buy you a couple beers. Do you have a PayPal account to contribute to? I really appreciate the hard work that has been put into this awesome Add-On!

**Comment by Mesuva** [comment]
Glad to hear that worked for you. 
I'll add that search indexing to my todo list of the project. Not sure when I'll get to it, but the solution you're using will totally fine to continue using.

Thanks for your kind words, and your offer to buy some beers (you're speaking the true currency of my people...). 

Perhaps drop me an email at ryan@mesuva.com.au and we can go from there. I'm really more interested to just hear what you're doing with Community Store.
