### ISSUE TITLE
EasyPost Issues once again

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store#624]
Website slowed way down again. Rebooted server and cleared my cache and got the EasyPost error about the required index thing again. Tried to delete the EasyPost shipping methods and get:
Property Concrete\Package\CommunityStoreEasypost\Src\CommunityStore\Shipping\Method\Types\EasypostShippingMethod::$id does not exist
So I decided enough of EasyPost and I cannot uninstall it.
Same error
Property Concrete\Package\CommunityStoreEasypost\Src\CommunityStore\Shipping\Method\Types\EasypostShippingMethod::$id does not exist

I assume you still can log in? You might still have cpanel login too? If not I'll send them to you if you're willing to look.
On Chrome the site is completely broken, but with Edge I can navigate the site, but cannot check out.

**Comment by mdius** [comment]
If you're able to completely remove EasyPost I'd prefer that.

**Comment by mdius** [comment]
Just noticed
Tried to enable a flat rate shipping method:
No identifier/primary key specified for Entity "Concrete\Package\CommunityStore\Src\CommunityStore\Shipping\Method\Types\FlatRateShippingMethod" sub class of "Concrete\Package\CommunityStore\Src\CommunityStore\Shipping\Method\ShippingMethodTypeMethod". Every Entity must have an identifier/primary key.

This was the error I always got from EasyPost, never affected the other methods.

**Comment by Mesuva** [comment]
Just taking a quick look now - site is coming up fine for me in Chrome, and I can add things to the cart and progress through the checkout.

The site does seem painfully slow at times though, at places where I wouldn't expect it to.
I'm wondering if the server is simply overloaded here, and the issues you are seeing are more to do with it timing out, rather than actual issues with Easypost.

**Comment by mdius** [comment]
I think it is server overload. But what's causing it?
I cannot edit any shipping method or add any either.

We talked about upgrading my shopping cart to the latest version before, you think that might clean things up? If so, email me.

**Comment by Mesuva** [comment]
We can certainly look at upgrading the site, but I'm pretty sure that it won't resolve the slowdowns.

It's more likely to be something like the sitemap being large, and then the autonav struggling to fetch all the pages it needs to to output the nav. And that processing might be maxing out what the server is prepared to allocate CPU wise to your site, and effectively limits everything. And the more product pages you've added over time, the worse it's become.

So you might require some site optimisations, rather than upgrades. There is an add-on that can help analyse such issues I believe.  I'm unlikely to have time tomorrow to email about this, but I can touch base early next week - if I'm not available to help, others might be able to offer their services too.

**Comment by mdius** [comment]
Yes, the sitemap added over a second to the load time, so I copied the HTML and put it in a HTML block.

So, I would like you to quote the optimization and the upgrade when you can. Early next week would be fine.
But to prove your point though, I just rebooted and cleared cache and it seems the issues have resolved, though I did it 2 times earlier with no luck.
Check out still seems to be extremely slow.
