### ISSUE TITLE
An issue has occured adding the product to the cart. You may be missing required information. 

### ISSUE THREAD

**Issue by baxterdmutt** [concretecms-community-store/community_store#695]
I am not sure where this error 

> An issue has occured adding the product to the cart. You may be missing required information. 

 is coming from.  I add an item to the cart, and when I click "checkout" this warning is there.  I've got through everything and can't seem to find any missing information. If I click "update" it goes away. If I ignore it and continue the check-out process, nothing bad happens. I am using the PayPal plugin, but again, I can't see anywhere this missing information it speaks of.
Anyone have an idea.
I am currently using php7.4 but tried 8.0  with bad results. Iv'e switched back and don't recall what he error was. Something to do with a key, but I'm not worried about that right now.

**Comment by Mesuva** [comment]
I'm not sure if I can work out what is happening in this case. That error message appears to be send if there's an error, but when there's not actual detail why. Is this just on a local site, or can you post a test URL for this issue?

**Comment by Mesuva** [comment]
Actually I've found the issue, I think it's something that happened due to a PHP8 fix.
Specifically this change here would be needed to fix: https://github.com/concretecms-community-store/community_store/commit/3c98e512595a3cbbd8249f05c99fef74ae7e7d97#diff-5d35ddfdf361b4584f54467908e67bb2c2eed2a71094b625b0603b42ca8f53c4L45

But I'll put out a new release in a few moment's time.

**Comment by baxterdmutt** [comment]
Thanks, That was fast!  It worked.
