### ISSUE TITLE
Version in file name prevents asset overrides

### ISSUE THREAD

**Issue by danklassen** [concretecms-community-store/community_store#730]
Including the `?v=$version` in the filename prevents the ability to copy a js file like `packages/community_store/js/communityStore.js` into `application/js/communityStore.js` as is typical for overriding package assets.

I'm not sure if this is by design to prevent these files from living in the application directory and eventually getting out of sync if the community_store package is upgraded or if this was to force browsers to download updated assets when a new version of the package is released. If it is the latter, clearing cache on a concrete-cms site greater than 8.5.8 updates the cache timestamps on any assets (https://github.com/concretecms/concretecms/issues/10483) which should address this scenario.

If you think this can be removed I can submit a PR with the change if it would be helpful

https://github.com/concretecms-community-store/community_store/blob/b4b69e6e546db4f8c88e075d9378cf27da6564ea/controller.php#L162-L167

**Comment by Mesuva** [comment]
This was originally by design to force a re-download of the script after a package upgrade, would have been ages ago that it was added in.
I didn't realise that would impact overriding though, something I've done myself in the past. 

I'd certainly prefer this to be done the correct way, so a PR would be greatly appreciated.
